[build]
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/hacker-loading.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[build.environment]
  NODE_VERSION = "16"

[dev]
  framework = "#static"
